//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactsDatalayer.ContactsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContactsService.IContactsService")]
    public interface IContactsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsService/GetContact", ReplyAction="http://tempuri.org/IContactsService/GetContactResponse")]
        ContactsShared.Contact GetContact(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsService/GetContactByPhone", ReplyAction="http://tempuri.org/IContactsService/GetContactByPhoneResponse")]
        ContactsShared.Contact GetContactByPhone(string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsService/GetContacts", ReplyAction="http://tempuri.org/IContactsService/GetContactsResponse")]
        System.Collections.Generic.List<ContactsShared.Contact> GetContacts(ContactsShared.ContactFilterArgs filterArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsService/Update", ReplyAction="http://tempuri.org/IContactsService/UpdateResponse")]
        bool Update(ContactsShared.Contact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsService/Create", ReplyAction="http://tempuri.org/IContactsService/CreateResponse")]
        bool Create(ContactsShared.Contact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsService/Remove", ReplyAction="http://tempuri.org/IContactsService/RemoveResponse")]
        bool Remove(System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContactsServiceChannel : ContactsDatalayer.ContactsService.IContactsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContactsServiceClient : System.ServiceModel.ClientBase<ContactsDatalayer.ContactsService.IContactsService>, ContactsDatalayer.ContactsService.IContactsService {
        
        public ContactsServiceClient() {
        }
        
        public ContactsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContactsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ContactsShared.Contact GetContact(System.Guid id) {
            return base.Channel.GetContact(id);
        }
        
        public ContactsShared.Contact GetContactByPhone(string phone) {
            return base.Channel.GetContactByPhone(phone);
        }
        
        public System.Collections.Generic.List<ContactsShared.Contact> GetContacts(ContactsShared.ContactFilterArgs filterArgs) {
            return base.Channel.GetContacts(filterArgs);
        }
        
        public bool Update(ContactsShared.Contact contact) {
            return base.Channel.Update(contact);
        }
        
        public bool Create(ContactsShared.Contact contact) {
            return base.Channel.Create(contact);
        }
        
        public bool Remove(System.Guid id) {
            return base.Channel.Remove(id);
        }
    }
}
